version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: postgres
      POSTGRES_DB: locallibrary
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    ports:
     - "3000:3000"
    restart: always
    depends_on:
    - "db"
    