version: '3.5'

services:
  app:
    build: .
    ports:
     - "3000:3000"
    restart: always
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    depends_on:
    - "app"